### ISSUE TITLE
include swift syntax highlighting

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/syntect-resources#8]

**Comment by mmatoszko** [comment]
Is it something which is hard to do? I would love to work on it, but I need some tips how this should be done

**Comment by cmyr** [comment]
No, this should not be hard! The steps are approximately as follows:

- find a good syntax definition (sublime or textmate) for the swift language, that has a permissive open source licence.
- add that syntax definition to this repo
- when that is merged, open a pr in the xi-editor repo that updates the `syntect-resources` submodule to include the new syntax definition
- update xi-mac to point to the new xi-editor
- write swift!

**Comment by cmyr** [comment]
And: you should be able to test out the syntax by just putting it in xi-mac/xi-editor/syntect-resources and rebuilding xi-mac.

**Comment by mmatoszko** [comment]
Thanks!

**Comment by mmatoszko** [comment]
Ok then.. I did some research and it looks like Swift Sublime Text packages are outdated. I will refresh my knowledge once in a while in order to support Swift 😄

**Comment by naclcaleb** [comment]
I found this, which has no license: https://github.com/GregoryBL/SwiftSyntax/blob/master/Swift.sublime-syntax

**Comment by cmyr** [comment]
From the [readme](https://github.com/GregoryBL/SwiftSyntax) it looks like MIT, so that's fine. we'll want to copy the license into a file if we take it on.

**Comment by naclcaleb** [comment]
Yes, sorry I was about to clarify that after reading the LICENSE section. I didn't see it before.

**Comment by cmyr** [comment]
This will also be quite out of date (it's at least two versoins of swift behind?) and it doesn't have metadata, but could be an okay starting point.

**Comment by naclcaleb** [comment]
We might be able to update it, but I don't know whether that would affect the licensing?

**Comment by cmyr** [comment]
Nope, we're free to do whatever we want, we're just expected to include the original license text intact. :)

**Comment by naclcaleb** [comment]
Ok, I'm making a PR as we speak...

**Comment by naclcaleb** [comment]
Ok, there you go. If that gets merged, I can follow through with a PR on xi-editor, and hopefully xi-mac as well.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
